import numpy as np
# Define the NumPy arrays
nparray1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
nparray2 = np.array([5, 6, 7, 8])
nparray3 = np.zeros((3, 4))
nparray4 = np.ones((3, 7))
# Perform slicing and display the results
print("nparray1:")
print (nparray1)
print("Selecting 1st 2 rows and 1st two columns:")
print (nparray1[:2, :2])
print("First element:")
print (nparray1[0, 0])
print("Middle element:")
print (nparray1[0, len (nparray1[0]) // 2])
print("Last element:")
print (nparray1[-1, -1])
print("\nnparray2:")
print (nparray2)
print("Selecting 1st two elements:")
print (nparray2[:2])
print("First element:")
print (nparray2 [0])
print("Middle element:")
print (nparray2[len (nparray2) // 2])
print("Last element:")
print (nparray2[-1])
print("\nnparray3:")
print (nparray3)
print("Selecting 1st 2 rows and 1st two columns:")
print (nparray3[:2, :2])
print("First element:")
print (nparray3[0, 0])
print("Middle element:")
print (nparray3[1, len (nparray3[1]) // 2])
print("Last element:")
print (nparray3[-1, -1])
print("\nnparray4:")
print (nparray4)
print("Selecting 1st 2 rows and 1st two columns:")
print (nparray4[:2, :2])
print("First element:")
print (nparray4[0, 0])
print("Middle element:")
print (nparray4[1, len (nparray4[1]) // 2])
print("Last element:")
print (nparray4[-1, -1])